#!/bin/sh
#
# Start Transmission Daemon
#

start() {
	printf "Starting Transmission: "
	start-stop-daemon -b -S -q -m -p /var/run/transmission.pid --exec transmission-daemon -- -a 192.168.*.*
	echo "OK"
}

stop() {
	printf "Stopping Miner: "
	start-stop-daemon -K -q -p /var/run/transmission.pid
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
