#!/bin/sh
#
# Start Transmission Daemon
#

start() {
	printf "Starting Transmission: "
	transmission-daemon -l 200 -L 5000 --auth --username=%USERNAME% --password=%PASSWORD% -a *.*.*.* -x /var/run/transmission.pid
	echo "OK"
}

stop() {
	printf "Stopping Transmission: "
	kill -9 $(cat /var/run/transmission.pid)
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
